---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.3.3"}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: php7-ubuntu-14.04
    run_list:
      - role[lamp-vagrant-ubuntu]
    includes:
      - ubuntu-14.04
  - name: php7-centos-7.2
    run_list:
      - role[lamp-vagrant-centos]
    includes:
      - centos-7.2
  - name: php5
    run_list:
      - role[lamp-vagrant-php5]
