name             'lamp'
maintainer       'Sergiu Ionescu'
maintainer_email 'sergiu.ionescu@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures lamp'
long_description 'Installs/Configures lamp with Berkshelf and Vagrant support'
version          '0.1.2'

depends 'apt'
depends 'mysql'
depends 'apache2'
depends 'php'
depends 'vim'
depends 'sendmail'

